#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include <stb/stb_image_resize.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb/stb_image_write.h>
#define CPP_UTILITY_IMPLEMENTATION
#include <Utility/CppUtility.hpp>
#define SOCKET_API_IMPLEMENTATION
#include <Utility/Socket.hpp>