#pragma once
#include "egx.hpp"
#include <memory/egxbuffer.hpp>
#include <memory/egximage.hpp>
#include <pipeline/Sampler.hpp>
#include <pipeline/pipeline.hpp>
#include <pipeline/RenderTarget.hpp>
#include <pipeline/DearImGuiController.hpp>
#include <pipeline/shaders/shader.hpp>
#include <pipeline/ShaderBinding.hpp>
#include <window/BitmapWindow.hpp>
#include <window/PlatformWindow.hpp>
#include <window/swapchain.hpp>
#include <scene/IScene.hpp>
#include <scene/CameraController.hpp>
#include "ScopedCommandBuffer.hpp"